#!/bin/bash

sudo apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev libyaml-dev libcurl4-openssl-dev
sudo apt-get install apache2 apache2-dev mysql
sudo apt-get install apache2-dev
sudo passenger-install-apache2-module --auto
